name: Deploy

on:
  push:
    branches: [master, main]

env:
  GH_USERNAME: Mogeko
  GH_EMAIL: zhengjunyi@live.com
  GH_REPO: github.com/Mogeko/mogeko.github.io
  GH_BRANCH: dist

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup yarn
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Run Build
        run: yarn build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist


  deploy:
    needs: [build, linter]
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Setup git
      run: |
        git config --global user.name "${GH_USERNAME}"
        git config --global user.email "${GH_EMAIL}"
    - name: Deploy to GitHub
      run: |
        git init && git add .
        for try_time in $(seq 0 9); do
          echo "Deploy the website"
          git commit -m "Build By GitHub Actions on $(date "+%Y-%m-%d %T")"
          if git push -f "https://${{ secrets.DEPLOY_TOKEN }}@${GH_REPO}" master:"${GH_BRANCH}"; then
            exit 0
          else
            echo "Deploy the website, retry: ${try_time}"
            sleep "$(shuf -i 3-10 -n 1)"
          fi
        done
        exit 1
